CREATE TABLE [dbo].[Comments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [VideoId] NVARCHAR(50) NOT NULL, 
    [UserId] NVARCHAR(50) NOT NULL, 
    [Content] NVARCHAR(MAX) NOT NULL
)
