CREATE TABLE [dbo].[JoinRequest]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
    [VideoId] NVARCHAR(50) NOT NULL, 
    [UserId] NVARCHAR(50) NOT NULL, 
    [JoinTime] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
)
