version: '3.7'
services:
  mongo:
    image: mongo
    #volumes:
    #  - ./data/mongo:/data/db
    ports: 
      - 27017:27017
  grpc-chat-sql:
    ports:
        - "1433:1433"
    image: grpc-chat-sql
    build: 
      context: ./sql
      dockerfile: "./grpc-chat/Dockerfile"
    restart: on-failure
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=grpcstreaming!Rul3s
  grpc-video-sql:
    ports:
        - "1434:1433"
    image: grpc-video-sql
    build: 
      context: ./sql
      dockerfile: "./grpc-video/Dockerfile"
    restart: on-failure
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=grpcstreaming!Rul3s
  redis:
    ports:
        - "6379:6379"
    image: redis:alpine
    restart: on-failure
  grpc-chat-server:
    ports:
        - "5000:5000"
    image: grpc-chat-server:latest
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:5000
  grpc-video-server:
    ports:
        - "5010:5010"
    image: grpc-video-server:latest
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:5010
  grpc-file-server:
    ports:
        - "50051:50051"
    image: grpc-file-server:latest
    restart: on-failure
    environment:
        - NODE_ENV=development
  grpc-web:
    ports:
        - "3000:3000"
    image: grpc-web:latest
    restart: on-failure
    environment:
        - NODE_ENV=development