version: '3.7'
services:
  mongo:
    image: mongo:4.2.0-rc2-bionic
    volumes:
      - ./data/mongo:/data/db
    ports: 
      - 27017:27017
  jenkins:
    image: jenkinsci/blueocean
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./home:/home
      - /var/run/docker.sock:/var/run/docker.sock
  npm-local:
    image: verdaccio/verdaccio:4.1.0
    restart: always
    ports:
      - "4873:4873"
    volumes:
      - npm-storage:/verdaccio
  nuget-local:
    image: idoop/docker-nuget-server:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      NUGET_API_KEY: "ea21e0d40b724c33a94580b832e6d0ca"
      SERVER_PORT: "8000"
      SERVER_NAME: "nuget-local"
    volumes:
      - nuget-db:/var/www/simple-nuget-server/db
      - nuget-packagefiles:/var/www/simple-nuget-server/packagefiles
      - nuget-nginx:/etc/nginx
volumes:
  npm-storage:
  nuget-db:
  nuget-packagefiles:
  nuget-nginx: